### PR TITLE
refactor!: modernize Reference

### PR DESCRIPTION
**Pull request by shizhMSFT**
### What this PR does / why we need it
Modernize `RemoteReference` to `Reference` witht dotnet / C# features.

### Which issue(s) this PR resolves / fixes
Resolve partially #91

### Please check the following list
- [x] Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [x] Does this change require a documentation update?
- [x] Does this introduce breaking changes that would require an announcement or bumping the major version?
- [x] Do all new files have an appropriate license header?

### CODE REVIEW

**Comment by sajayantony** [comment]
Are you planning to bring up the code coverage for this? The changes are really good.

**Comment by sajayantony** [comment]
Are you planning to bring up the code covage for this? The changes are really good.

**Comment by shizhMSFT** [comment]
> Are you planning to bring up the code coverage for this? The changes are really good.

The purpose of this set of PRs are to modernize the code (i.e. focusing on interfaces). Perf improvement and code coverage will be future works.

**Review by Wwwsylvia — APPROVED** [review]
LGTM

**Pull request merged**
